/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersStafRouteImport } from './routes/_app.users-staf'
import { Route as AppUsersClientRouteImport } from './routes/_app.users-client'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOtcMintRouteImport } from './routes/_app.otc-mint'
import { Route as AppOtcBurnRouteImport } from './routes/_app.otc-burn'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersStafRoute = AppUsersStafRouteImport.update({
  id: '/users-staf',
  path: '/users-staf',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersClientRoute = AppUsersClientRouteImport.update({
  id: '/users-client',
  path: '/users-client',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOtcMintRoute = AppOtcMintRouteImport.update({
  id: '/otc-mint',
  path: '/otc-mint',
  getParentRoute: () => AppRoute,
} as any)
const AppOtcBurnRoute = AppOtcBurnRouteImport.update({
  id: '/otc-burn',
  path: '/otc-burn',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/otc-burn': typeof AppOtcBurnRoute
  '/otc-mint': typeof AppOtcMintRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/users-client': typeof AppUsersClientRoute
  '/users-staf': typeof AppUsersStafRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/otc-burn': typeof AppOtcBurnRoute
  '/otc-mint': typeof AppOtcMintRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/users-client': typeof AppUsersClientRoute
  '/users-staf': typeof AppUsersStafRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/otc-burn': typeof AppOtcBurnRoute
  '/_app/otc-mint': typeof AppOtcMintRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/report': typeof AppReportRoute
  '/_app/users-client': typeof AppUsersClientRoute
  '/_app/users-staf': typeof AppUsersStafRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otc-burn'
    | '/otc-mint'
    | '/profile'
    | '/report'
    | '/users-client'
    | '/users-staf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/otc-burn'
    | '/otc-mint'
    | '/profile'
    | '/report'
    | '/users-client'
    | '/users-staf'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/otc-burn'
    | '/_app/otc-mint'
    | '/_app/profile'
    | '/_app/report'
    | '/_app/users-client'
    | '/_app/users-staf'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users-staf': {
      id: '/_app/users-staf'
      path: '/users-staf'
      fullPath: '/users-staf'
      preLoaderRoute: typeof AppUsersStafRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users-client': {
      id: '/_app/users-client'
      path: '/users-client'
      fullPath: '/users-client'
      preLoaderRoute: typeof AppUsersClientRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/otc-mint': {
      id: '/_app/otc-mint'
      path: '/otc-mint'
      fullPath: '/otc-mint'
      preLoaderRoute: typeof AppOtcMintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/otc-burn': {
      id: '/_app/otc-burn'
      path: '/otc-burn'
      fullPath: '/otc-burn'
      preLoaderRoute: typeof AppOtcBurnRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOtcBurnRoute: typeof AppOtcBurnRoute
  AppOtcMintRoute: typeof AppOtcMintRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportRoute: typeof AppReportRoute
  AppUsersClientRoute: typeof AppUsersClientRoute
  AppUsersStafRoute: typeof AppUsersStafRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOtcBurnRoute: AppOtcBurnRoute,
  AppOtcMintRoute: AppOtcMintRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportRoute: AppReportRoute,
  AppUsersClientRoute: AppUsersClientRoute,
  AppUsersStafRoute: AppUsersStafRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
